<a href="https://colab.research.google.com/github/AlexBecerril/miaad-sem1/blob/main/S06_Actividad_02_ALGEBRALINEAL_MATRICULA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**
Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [36]:
import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [37]:
#calidad, precio, servicio
producto_A = np.array([4.5, 3.2, 5.0])
producto_B = np.array([4.0, 2.8, 4.7])
producto_C = np.array([1.0, 5.0, 1.2])

print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [38]:
#La norma representa la longitud o magnitud del vector y se obtiene elevando cada uno de sus elementos al cuadrado y luego sacando la raíz cuadrada al resultado
n_a = np.linalg.norm(producto_A)
n_b = np.linalg.norm(producto_B)
n_c = np.linalg.norm(producto_C)
print("Norma de producto A: ", n_a)
print("Norma de producto B: ", n_b)
print("Norma de producto C: ", n_c)

Norma de producto A:  7.449161026585477
Norma de producto B:  6.777167549942971
Norma de producto C:  5.238320341483518


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [39]:
#El Producto punto es una operación entre dos vectores que multiplica sus elementos correspondientes y suma los resultados.
#Sirve para medir la relación entre dos vectores, por ejemplo, determinar si son ortogonales o qué tan alineadas están sus direcciones.
#Producto punto > 0: los vectores apuntan en direcciones similares.
#Producto punto = 0: los vectores son ortogonales (perpendiculares).
#Producto punto < 0: los vectores apuntan en direcciones opuestas.
p_ab = np.dot(producto_A, producto_B)
p_ac = np.dot(producto_A, producto_C)
print("Producto punto entre los productos A y B: ", p_ab)
print("Producto punto entre los productos A y C: ", p_ac)

angulo_ab = np.degrees(np.arccos(p_ab / (n_a * n_b)))
angulo_ac = np.degrees(np.arccos(p_ac / (n_a * n_c)))
print("Angulo entre los productos A y B: ", angulo_ab)
print("Angulo entre los productos A y C: ", angulo_ac)

#El producto A y B son más parecidos entre ellos ya que su angulo es de tan solo 1.7 grados
#lo que quiere decir que estan muy cerca, por otro lado la distancia entre A y C es de 47 grados

Producto punto entre los productos A y B:  50.46
Producto punto entre los productos A y C:  26.5
Angulo entre los productos A y B:  1.7745815839558179
Angulo entre los productos A y C:  47.22509268261831


---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [40]:
#Normalizar vectores sirve para eliminar el efecto de su magnitud y comparar únicamente su dirección.
producto_A_norm = producto_A / n_a
print("Producto A normalizado: ", producto_A_norm)
print("Norma de producto A normalizado: ", np.linalg.norm(producto_A_norm))
producto_B_norm = producto_B / n_b
print("Producto B normalizado: ", producto_B_norm)
print("Norma de producto B normalizado: ", np.linalg.norm(producto_B_norm))
producto_C_norm = producto_C / n_c
print("Producto C normalizado: ", producto_C_norm)
print("Norma de producto C normalizado: ", np.linalg.norm(producto_C_norm))

Producto A normalizado:  [0.60409488 0.42957858 0.67121653]
Norma de producto A normalizado:  1.0
Producto B normalizado:  [0.59021707 0.41315195 0.69350506]
Norma de producto B normalizado:  1.0
Producto C normalizado:  [0.19090089 0.95450444 0.22908106]
Norma de producto C normalizado:  1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [41]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [42]:
#Cuando utilizamos * se multiplica cada elemento por el elemento correspondiente de la segunda matriz.
#Para obtener el elemento 0,0 de la matriz resultante se multiplica A(0,0) * B(0,0) y asi sucesivamente
print("M * P")
print(M * P)
print("\n")
#Cuando utilizamos @ se efectua una multiplicación matricial, de modo que
#para obtener el valor del elemento (0,0) de la matriz resultante se ejecuta A(0,0) * B(0,0) + A(0,1) * B(1,0)
#para obtener el valor del elemento (0,1) de la matriz resultante se ejecuta A(0,0) * B(0,1) + A(0,1) * B(1,1)
#para obtener el valor del elemento (1,0) de la matriz resultante se ejecuta A(1,0) * B(0,0) + A(1,1) * B(1,0)
#para obtener el valor del elemento (1,1) de la matriz resultante se ejecuta A(1,0) * B(0,1) + A(1,1) * B(1,1)
print("M @ P")
print(M @ P)
print("\n")
#Dos matrices se pueden multiplicar cuando el numero de las columnas de la primera es igual al numero de filas de la segunda
#lo podemos comprobar con shape
print("forma de M: ", M.shape)
print("forma de P: ", P.shape)
print("\n")
# A diferencia de la multiplicación de escalares, en la multiplicación
# matricial el orden de los factores sí afecta el resultado, ya que
# en general M @ P != P @ M.
print("P @ M")
print(P @ M)

M * P
[[3. 0.]
 [0. 6.]]


M @ P
[[3.  2. ]
 [1.5 6. ]]


forma de M:  (2, 2)
forma de P:  (2, 2)


P @ M
[[3.  1.5]
 [2.  6. ]]


---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [43]:
# Tu código aquí
print(M)
print("\n")
print("Determinante de M: ", np.linalg.det(M))
print("M es invertible?: ", np.linalg.det(M) != 0)
print("\n")
M_inv = np.linalg.inv(M)
print("Inversa de M:")
print(M_inv)
print("\n")
print("M @ M_inv:")
print(M @ M_inv)


[[2 1]
 [1 3]]


Determinante de M:  5.000000000000001
M es invertible?:  True


Inversa de M:
[[ 0.6 -0.2]
 [-0.2  0.4]]


M @ M_inv:
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [44]:
print("Proporciones:")
print(M)
print("\n")

b = np.array([180, 300])

# Tu código aquí
x = np.linalg.solve(M, b)
print("Cantidades necesarias de cada insumo: ")
print(x)

print("\n")
print("Numero de unidades de cada linea")
print(M @ x)


Proporciones:
[[2 1]
 [1 3]]


Cantidades necesarias de cada insumo: 
[48. 84.]


Numero de unidades de cada linea
[180. 300.]


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [45]:
# Tu código aquí
print("distancia entre producto A y B: ", np.linalg.norm(producto_A - producto_B))
print("distancia entre producto A y C: ", np.linalg.norm(producto_A - producto_C))
print("similitud coseno entre producto A y B: ", p_ab / (n_a * n_b))
print("similitud coseno entre producto A y C: ", p_ac / (n_a * n_c))

print("La distancia entre A y B es de menos de 1, la diferencia entre A y C es de 5.4, por lo tanto A y B son más parecidos")
print("La similitud entre A y B es de menos de 0.99, la similitud entre A y C es de 0.67, por lo tanto A y B son más parecidos")
print("ambas métricas llegan a la misma conclusión: A y B son más parecidos que A y C")

distancia entre producto A y B:  0.7071067811865476
distancia entre producto A y C:  5.470831746635972
similitud coseno entre producto A y B:  0.9995203969214979
similitud coseno entre producto A y C:  0.6791199021706347
La distancia entre A y B es de menos de 1, la diferencia entre A y C es de 5.4, por lo tanto A y B son más parecidos
La similitud entre A y B es de menos de 0.99, la similitud entre A y C es de 0.67, por lo tanto A y B son más parecidos
ambas métricas llegan a la misma conclusión: A y B son más parecidos que A y C


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.